[tool.poetry]
name = "tg-playme-002"
version = "0.1.0"
description = ""
authors = ["Vionaaru <d.s.kasimov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
environs = "^11.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
